# Generated by Django 4.2.5 on 2023-10-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_vehicle_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='charger_types',
            field=models.CharField(max_length=200),
        ),
    ]
