# Generated by Django 4.2.5 on 2023-10-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_station_charger_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='elevation2',
        ),
    ]
