# Generated by Django 4.2.5 on 2023-10-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_operation_elevation2'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='elevation2',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
