# Generated by Django 4.2.5 on 2023-10-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_operation_elevation2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='vehicle_id',
            field=models.CharField(max_length=6),
        ),
    ]
