# Generated by Django 4.2.5 on 2023-10-21 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_operation_vehicle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='user_email',
        ),
    ]
