# Generated by Django 4.2.5 on 2023-10-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_remove_operation_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='charger_type',
            field=models.CharField(default='', max_length=64),
        ),
    ]
